--<ScriptOptions statementTerminator=";"/>

CREATE TABLE CHARGES (
	ID INT NOT NULL,
	AMOUNT DECIMAL(10 , 2),
	CHARGE_DATE TIMESTAMP,
	EXPENSE_ITEM_ID INT,
	PRIMARY KEY (ID)
);

CREATE TABLE SALES (
	ID INT NOT NULL,
	AMOUNT DECIMAL(10 , 2),
	QUANTITY INT,
	SALE_DATE TIMESTAMP,
	WAREHOUSE_ID INT,
	PRIMARY KEY (ID)
);

CREATE TABLE WAREHOUSES (
	ID INT NOT NULL,
	NAME VARCHAR(50),
	QUANTITY INT,
	AMOUNT DECIMAL(10 , 2),
	PRIMARY KEY (ID)
);

CREATE TABLE EXPENSE_ITEMS (
	ID INT NOT NULL,
	NAME VARCHAR(100),
	PRIMARY KEY (ID)
);

CREATE INDEX WAREHOUSE_ID ON SALES (WAREHOUSE_ID ASC);

CREATE INDEX EXPENSE_ITEM_ID ON CHARGES (EXPENSE_ITEM_ID ASC);

